### ISSUE TITLE
synchashes could not continue after first fail

### ISSUE THREAD

**Issue by danixeee** [openlawlibrary/OLAAF-Transient#22]
`synchashes` command could not continue to insert the data if it failed earlier. It tries to insert `Hash` object without `Path` reference to the database.

Fails at line `Hash.objects.bulk_create(hashes_by_paths_and_types.values())`.

**Comment by renatav** [comment]
It appears that this was caused by two synchashes instances running at the same time. synchashes is successfully completed in cases when paths exist and commits don't. I think that we can close this issue
